### ISSUE TITLE
console.log problem in editor

### ISSUE THREAD

**Issue by junedev** [exercism/typescript-test-runner#28]
From the editor bug reports:

> Hello, I am unable to use the console.log() function to perform debugging. When I add the line, it always says {Try changing the 'lib' compiler option to include 'dom'}. Would request you to kindly look into it

**Comment by SleeplessByte** [comment]
Hi @James-N-M ! Yes you may. The issue is likely [here](https://github.com/exercism/typescript-test-runner/blob/main/bin/run.sh#L124-L134) in [`run.sh`](https://github.com/exercism/typescript-test-runner/blob/main/bin/run.sh#L124-L134). Copying the types also doesn't work, because we had to disable the tests in order to make this work (`describe` and `it` could not be found).

I didn't have time to investigate. It's _very_ likely that all we need is "just" change `tsconfig.json` in the input directory to resolve this, and make sure that that `tsc` call picks up _that_ `tsconfig.json`.

Find the interface for the test runner at <https://exercism.org/docs/building/tooling/test-runners/interface>, to help you understand _how_ it's ran.

**Comment by James-N-M** [comment]
Not sure if anyone else is getting this issue when running the file, I'm not sure if its my node version or yarn version.

node: v12.19.0
yarn: 1.22.10

<img width="827" alt="Screen Shot 2021-10-09 at 11 45 58 AM" src="https://user-images.githubusercontent.com/6562688/136665330-731dc575-dded-4abc-94bf-cd5285f04a85.png">

**Comment by James-N-M** [comment]
I think the bash script might be wrong, I'm going to look at other test runners to see if I can spot differences. New to Bash scripting but I'm happy to learn :)

**Comment by SleeplessByte** [comment]
Possible that it's actually not bourne-compatible and thus bash specific. It should just be https only though, so you can remove the ?( and ) and retry.

**Comment by SleeplessByte** [comment]
Should have been resolved
