### ISSUE TITLE
Possible TypeScript version mismatch (highlighted by solution for word-count exercise)

### ISSUE THREAD

**Issue by harry-graham** [exercism/typescript-test-runner#56]
On the "word-count" exercise, the tests passed locally for me, but when run on Exercism, threw an error:
> error TS1384: A 'new' expression with type arguments must always be followed by a parenthesized argument list.

The issue was the following line in my solution:
```typescript
const result = new Map<string, number>;
```
Changing it to the below fixed it:
```typescript
const result = new Map<string, number>();
```

Checking the current main branch of TypeScript's source code repo, we can see that the error code TS1384 no longer exists in the [diagnostic messages file](https://github.com/microsoft/TypeScript/blob/main/src/compiler/diagnosticMessages.json#L1199-L1206).

I see in the `package.json` for the TypeScript exercises, the development dependency version for TypeScript is listed `^4.5.4`, i.e. v4.5.4 and above, whilst TypeScript's latest version is v4.9.4 (which I'm running locally).

**Comment by SleeplessByte** [comment]
Whilst `new Map` (and the TypeScript equivalent `new Map<K, V>`) are valid syntax, I highly recommend against writing a class instantiation without parameters because using the parameters is the defacto standard.

Your assertion is likely to be correct. It's possible that this is because of the version mismatch. We periodically update the track, test runner, and analyzer, but because this also means we now need to support all new changes (in the analyzer especially) we don't do it as soon as a new version comes out.

Can you live with the lower version for a while @harry-graham ?

**Comment by harry-graham** [comment]
@SleeplessByte thanks, yes sure, no rush. I just wanted to write the issue somewhere, to possibly help anyone else who might run into a similar issue.
